config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  resources :blog_posts
  # Blog Routes
  # get "/blog_posts/new", to: "blog_posts#new", as: :new_blog_post
  # get "/blog_posts/:id_or_slug", to: "blog_posts#show", as: :blog_post
  # patch "/blog_posts/:id_or_slug", to: "blog_posts#update"
  # delete "/blog_posts/:id_or_slug", to: "blog_posts#destroy"
  # get "/blog_posts/:id_or_slug/edit", to: "blog_posts#edit", as: :edit_blog_post
  # post "/blog_post", to: "blog_posts#create", as: :blog_posts

  # Defines the root path route ("/")
  root "blog_posts#index"

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/blog_post.rb
class BlogPost < ApplicationRecord
  has_rich_text :content
  after_initialize :set_default_values
  before_save :generate_slug
  validates :title, presence: true
  validates :content, presence: true

  # scope :sorted, -> {order(published_at: :desc, updated_at: :desc)}
  scope :sorted, -> { order(Arel.sql("#{arel_table[:published_at].desc.nulls_first.to_sql}, updated_at DESC")) }
  scope :draft, -> { where(published_at: nil) }
  scope :published, -> { where("published_at <= ?", Time.current) }
  scope :scheduled, -> { where("published_at > ?", Time.current) }

  def draft?
    published_at.nil?
  end

  def published?
    published_at? && published_at <= Time.current
  end

  def scheduled?
    published_at? && published_at > Time.current
  end


  private

  def generate_slug
    self.slug = title.parameterize
  end
  def set_default_values
    self.published_at ||= nil
  end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  # :registerable
  devise :database_authenticatable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/blog_posts_controller.rb
class BlogPostsController < ApplicationController
  before_action :authenticate_user!, except: [:index, :show]
  before_action :find_blog_post, except: [:index, :new, :create]

  def index
    if user_signed_in?
      @blog_posts = BlogPost.sorted.paginate(page: params[:page], per_page: 2)
    else
      @blog_posts = BlogPost.published.sorted.paginate(page: params[:page], per_page: 2)
    end
  end
  

  def show
    if @blog_post.nil?
      redirect_to root_path, alert: "Blog post not found"
    end
  rescue ActiveRecord::RecordNotFound
    redirect_to root_path
  end

  def new
    @blog_post = BlogPost.new
    @blog_post.published_at = nil
  end

  def create
    @blog_post = BlogPost.new(blog_post_params)
    existing_post = BlogPost.find_by(title: @blog_post.title)
    if existing_post
      flash[:error] = "A blog post with the same title already exists."
      render :new
    elsif @blog_post.save
      redirect_to @blog_post
    else
      render :new, status: :unprocessable_entity
    end
  end
  

  def edit
    if @blog_post.nil?
      redirect_to root_path, alert: "Blog post not found"
    end
  rescue ActiveRecord::RecordNotFound
    redirect_to root_path
  end

  def update
    if @blog_post.update(blog_post_params)
      redirect_to @blog_post
    else
      render :edit, status: :unprocessable_entity
    end
  end
  
  def destroy
    if @blog_post.destroy
      redirect_to root_path, notice: "Blog post was successfully deleted."
    else
      redirect_to @blog_post, alert: "Failed to delete blog post."
    end
end


  private

  def blog_post_params
    params.require(:blog_post).permit(:title, :content, :published_at)
  end

  def find_blog_post
    id_or_slug = params[:id]

    if id_or_slug.to_i.to_s == id_or_slug
      # If the parameter is a number, treat it as an ID
      @blog_post = current_user ? BlogPost.find(id_or_slug) : BlogPost.published.find(id_or_slug)
    elsif id_or_slug.present?
      # If the parameter is not a number and is present, treat it as a title
      slug = id_or_slug.parameterize
      @blog_post = current_user ? BlogPost.find_by(slug: slug) : BlogPost.published.find_by(slug: slug)
    else
      # Handle the case when id_or_slug is not present (e.g., show a flash message or redirect)
      redirect_to root_path, alert: "Invalid blog post identifier"
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
    def truncate_rich_text(content, length: 150, omission: '...')
        stripped_content = strip_tags(content.to_s)
        truncated_text = truncate(stripped_content, length: length, omission: omission)
        sanitize(truncated_text, tags: %w(p br)) # Ensure HTML tags are preserved
    end 
end

app/views/active_storage/blobs/_blob.html.erb
<figure class="attachment attachment--<%= blob.representable? ? "preview" : "file" %> attachment--<%= blob.filename.extension %>">
  <% if blob.representable? %>
    <%= image_tag blob.representation(resize_to_limit: local_assigns[:in_gallery] ? [ 800, 600 ] : [ 1024, 768 ]) %>
  <% end %>

  <figcaption class="attachment__caption">
    <% if caption = blob.try(:caption) %>
      <%= caption %>
    <% else %>
      <span class="attachment__name"><%= blob.filename %></span>
      <span class="attachment__size"><%= number_to_human_size blob.byte_size %></span>
    <% end %>
  </figcaption>
</figure>

app/views/blog_posts/_form.html.erb
<div class="">
  <% if flash[:error] %>
    <div class="mb-4 bg-red-100 border border-red-400 text-red-700 px-4 py-2 rounded-md">
      <h2 class="text-lg font-semibold">Error:</h2>
      <p><%= flash[:error] %></p>
    </div>
  <% end %>
  <%= form_with model: @blog_post, html: { class: 'space-y-4' } do |form| %>
    <% if @blog_post.errors.any? %>
      <div class="mb-4 bg-yellow-100 border border-yellow-400 text-yellow-700 px-4 py-2 rounded-md">
        <h2 class="text-lg font-semibold">Validation Errors:</h2>
        <ul>
          <% @blog_post.errors.full_messages.each do |message| %>
            <li><%= message %></li>
          <% end %>
        </ul>
      </div>
    <% end %>
    <div>
      <%= form.label :title, class: 'block text-sm font-medium text-gray-700' %>
      <%= form.text_field :title, class: 'w-full px-4 py-2 border rounded-md focus:outline-none focus:border-blue-500' %>
    </div>
    <div>
      <%= form.label :content, class: 'block text-sm font-medium text-gray-700' %>
      <%= form.rich_text_area  :content, class: 'w-full px-4 py-2 border rounded-md focus:outline-none focus:border-blue-500' %>
    </div>
    <div>
      <%= form.label :published_at, class: 'block text-sm font-medium text-gray-700' %>
      <%= form.datetime_select :published_at, {
          start_year: Time.current.year,
          include_blank: true,
          ampm: true,
          class: 'w-full px-4 py-2 border rounded-md focus:outline-none focus:border-blue-500'
        } %>
    </div>
    <div class="flex items-center justify-center space-x-4 mt-4">
      <% if @blog_post.new_record? %>
        <%= form.submit "Create Blog Post", class: ' bg-blue-500 text-white px-4 py-2 rounded-md hover:bg-blue-600 focus:outline-none focus:shadow-outline-blue active:bg-blue-800' %>
      <% else %>
        <%= form.submit "Update Blog Post", class: 'bg-green-500 text-white px-4 py-2 rounded-md hover:bg-green-600 focus:outline-none focus:shadow-outline-green active:bg-green-800' %>
        <% if !@blog_post.new_record? %>
          <div class="flex items-center justify-center space-x-4">
            <%= button_to "Delete", @blog_post, method: :delete, class: 'bg-red-500 text-white px-4 py-2 rounded-md hover:bg-red-600 focus:outline-none focus:shadow-outline-red active:bg-red-800', data: { turbo_confirm: 'Are you sure?' } %>
          </div>
        <% end %>
      <% end %>
    </div>
  <% end %>
</div>

app/views/blog_posts/edit.html.erb
<div class=" mx-auto mt-8 p-6 bg-white rounded-md shadow-md">
  <h1 class="text-2xl text-center font-semibold mb-6">Edit Blog Post</h1>
  <%= render "form", locals: { blog_post: @blog_post } %>
</div>

app/views/blog_posts/index.html.erb
<div class="grid grid-cols-1 gap-1">
  <% @blog_posts.each do |blog_post| %>
    <div class="border-t-2 border-gray-300 py-8 flex">
      <div class="flex items-center justify-start w-1/3">
        <p class="text-[#261b21] text-start text-xl font-semibold">
          <%= render partial: 'shared/published_info', locals: { blog_post: blog_post } %>
        </p>
      </div>
      <div class="w-full">
        <% button_options = "mt-2 text-[#968D8F] text-sm font-semibold leading-6 " %>
        <h3 class="text-[#d30001] text-3xl font-bold underline hover:text-[#261b21] transition">
          <%= link_to blog_post.title, blog_post.slug.present? ? blog_post_path(blog_post.slug) : blog_post %>
        </h3>
        <% if user_signed_in? %>
          <div class="flex items-center justify-start">
            <%= render 'shared/status_buttons', button_options: button_options, blog_post: blog_post %>
          </div>
        <% end %>
        <p class="text-[#5A5153] text-base leading-6 mt-4">
          <% truncate_rich_text(blog_post.content) %>
        </p>
      </div>
    </div>
  <% end %>
</div>
<div class="border-t-2 border-gray-300 py-8 flex items-center justify-center">
  <%= will_paginate @blog_posts %>
</div>

app/views/blog_posts/new.html.erb
<div class=" mx-auto mt-8 p-6 bg-white rounded-md shadow-md">
  <h1 class="text-2xl text-center font-semibold mb-6">New Blog Post</h1>
  <%= render "form", locals: { blog_post: @blog_post } %>
</div>

app/views/blog_posts/show.html.erb
<div class="mx-auto mt-8 p-6 bg-white rounded-md text-center shadow-md">
  <p class="text-[#261B23] text-base font-semibold tracking-tighter leading-6 mb-3">
    <%= render partial: 'shared/published_info', locals: { blog_post: @blog_post } %>
  </p>
  <h3 class="text-[#D30001] text-5xl font-bold leading-tight tracking-tighter">
    <%= @blog_post.title %>
  </h3>
  <% if user_signed_in? %>
    <div class="flex items-center justify-center p-4 mt-2 pb-1">
      <% button_options = "mr-4 text-[#968D8F] text-lg font-semibold leading-6 bg-[#F2F2F2] rounded-full px-4 py-2 hover:text-[#5A5153] transition-colors duration-300" %>
      <%= link_to "Slug: " + @blog_post.slug, blog_post_path(@blog_post.slug), class: button_options %>
      <%= link_to "ID: " + @blog_post.id.to_s, blog_post_path(@blog_post), class: button_options %>
      <%= render 'shared/status_buttons', button_options: button_options, blog_post: @blog_post %>
      <%= link_to "Edit Blog Post", edit_blog_post_path(@blog_post), class: "text-white bg-blue-500 hover:bg-blue-700 rounded-full px-4 py-2" %>
    </div>
  <% end %>
  <div class="border-t-2 border-gray-300 pt-8 mt-11">
    <p class="text-[#5A5153] text-base">
      <%= @blog_post.content %>
    </p>
  </div>
</div>

app/views/layouts/action_text/contents/_content.html.erb
<div class="trix-content">
  <%= yield -%>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="turbo-visit-control" content="reload">
    <title>Blog</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= turbo_include_tags %>
    <%= stylesheet_link_tag "tailwind", "inter-font", "data-turbo-track": "reload" %>
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= stylesheet_link_tag "actiontext", "data-turbo-track": "reload" %>
    <%# javascript_importmap_tags %>
    
  </head>
  <body class="font-sans antialiased">
    <div class="container w-3/4 mx-auto p-4">
      <!-- Logo Section -->
      <div class="mb-8 text-center logo-container">
        <div class="logo"></div>
      </div>
      <!-- Menu Section -->
      <% unless controller_name == 'blog_posts' && action_name == 'show' %>
        <nav class="mb-8 flex justify-center items-center">
          <!-- Your Navigation Menu Goes Here -->
          <ul class="flex justify-center space-x-4 bg-none border-none">
            <li><%= link_to "Everything", root_path, class: "nav-link" %></li>
            <li><%= link_to "Releases", root_path, class: "nav-link" %></li>
            <li><%= link_to "News", root_path, class: "nav-link" %></li>
            <!-- Add more menu items as needed -->
          </ul>
          <!-- Logout Button and New Blog Post -->
          <div class="flex justify-center items-center ml-4 text-xl font-semibold">
            <% if user_signed_in? %>
              <%= link_to "New Post", new_blog_post_path, class: "bg-blue-500 text-white px-4 py-2 rounded-md hover:bg-blue-600 focus:outline-none focus:shadow-outline-blue active:bg-blue-800" %>
              <%= button_to "Log out", destroy_user_session_path, method: :delete, class: "ml-4 bg-red-500 text-white px-4 py-2 rounded-md hover:bg-red-600 focus:outline-none focus:shadow-outline-red active:bg-red-800" %>
            <% end %>
          </div>
        </nav>
      <% end %>
      <!-- Content Section -->
      <div class="mb-8">
        <%= yield %>
      </div>
    </div>
    <!-- Footer Section -->
    <footer class="bg-[#F0E7E9] w-full py-4 text-center footer">
      <!-- Your Footer Content Goes Here -->
      <div class="footer-logo">
        <a href="/" aria-label="Ruby on Rails" class=""></a>
      </div>
    </footer>
  </body>
</html>

app/views/shared/_published_info.html.erb
<% if blog_post.published? %>
  <%= blog_post.published_at.strftime('%B %d, %Y') %>
<% elsif blog_post.scheduled? %>
  <%= blog_post.published_at.strftime('%B %d, %Y') %>
<% else %>
  <%= blog_post.created_at.strftime('%B %d, %Y') %>
<% end %>

app/views/shared/_status_buttons.html.erb
<%= link_to edit_blog_post_path(blog_post) do %>
  <% if blog_post.present? %>
    <% if blog_post.draft? %>
      <%= button_to "Draft", "", class: button_options %>
    <% elsif blog_post.scheduled? %>
      <%= button_to "Scheduled", "", class: button_options %>
    <% elsif blog_post.published? %>
      <%= button_to "Published", "", class: button_options %>
    <% end %>
  <% end %>
<% end %>

app/views/turbo_streams/remove_blog_post.turbo_stream.erb
<turbo-stream action="remove" target="blog_post_<%= @blog_post.id %>">
</turbo-stream>